//CART
export const REQUEST_GET_PRODUCTS_IN_CART = "REQUEST_GET_PRODUCTS_IN_CART";
export const GET_PRODUCTS_IN_CART_SUCCESS = "GET_PRODUCTS_IN_CART_SUCCESS";
export const GET_PRODUCTS_IN_CART_FAIL = "GET_PRODUCTS_IN_CART_FAIL";
export const REQUEST_EDIT_PRODUCT_IN_CART = "REQUEST_EDIT_PRODUCT_IN_CART";
export const EDIT_PRODUCT_IN_CART_SUCCESS = "EDIT_PRODUCT_IN_CART_SUCCESS";
export const EDIT_PRODUCT_IN_CART_FAIL = "EDIT_PRODUCT_IN_CART_FAIL";
export const REQUEST_DELETE_PRODUCT_IN_CART = "REQUEST_DELETE_PRODUCT_IN_CART";
export const DELETE_PRODUCT_IN_CART_SUCCESS = "DELETE_PRODUCT_IN_CART_SUCCESS";
export const DELETE_PRODUCT_IN_CART_FAIL = "DELETE_PRODUCT_IN_CART_FAIL";
export const REQUEST_ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILED = "ADD_PRODUCT_TO_CART_FAILED";

//PRODUCT
export const REQUEST_GET_PRODUCT = "REQUEST_GET_PRODUCT";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_USER_DATA = 'SET_USER_DATA'
export const LOGOUT = "LOGOUT"
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const REQUEST_GET_INFO = 'REQUEST_GET_INFO';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';
export const REQUEST_EDIT_INFO = 'REQUEST_EDIT_INFO';
export const EDIT_INFO_SUCCESS = 'EDIT_INFO_SUCCESS';
export const EDIT_INFO_FAIL = 'EDIT_INFO_FAIL';

// ORDER
export const REQUEST_GET_ORDERS = "REQUEST_GET_ORDERS";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED"
export const REQUEST_ADD_ORDER = "REQUEST_ADD_ORDER";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILED = "ADD_ORDER_FAILED";
